### ISSUE TITLE
Will this work on Linux

### ISSUE THREAD

**Issue by GabMus** [crashniels/GloriousModelORGBControl#1]
Hey there, I stumbled upon this project, and while I'm not that great with C(++) I seem to understand that this software makes use of libusb to send raw data packets to the mouse to be able to control it's lighting, is that so?

I was wondering if you were planning on supporting linux, and if there are any blockers right now for linux support.

Thanks a lot.

**Comment by crashniels** [comment]
Hello. This project was made with JackNet RGBSync in mind but it could theoretically be added to open source projects like OpenRGB on GitLab since the protocol is already there. As of now i have not found a way of sending the RGB directly but rather spamming the static profile. This causes the moues pointer to sometimes do weird things when applying fast effects like music visualizers.

**Comment by crashniels** [comment]
@GabMus I made a PR on OpenRGB with the Model O. It should work in both Windows and Linux with that build. I heard that the Model O can change it's Product ID which would not make it detect in OpenRGB. Mine is in there but others are not.

**Comment by crashniels** [comment]
Closing as already implemented through OpenRGB.
